// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a custom sidebar to ensure the order and structure
  docsSidebar: [
    {
      type: 'category',
      label: 'Yeap Finance',
      link: {
        type: 'generated-index',
        title: 'Yeap Finance Overview',
        description: 'Learn about the core concepts and architecture of Yeap Finance, the multi-protocol engine for decentralized lending.',
        slug: '/overview'
      },
      items: [
        'introduction', // Corresponds to docs/introduction.md
        'architecture', // Corresponds to docs/architecture.md
      ],
    },
    {
      type: 'category',
      label: 'Core Components',
      items: [
        'core-components/vaults', // Corresponds to docs/core-components/vaults.md
        'core-components/borrow-protocols', // Corresponds to docs/core-components/borrow-protocols.md
        // Add more items as you create files for sub-sections like IBTs, IRMs etc.
      ],
    },
    {
      type: 'category',
      label: 'Key Features',
      items: [
        'key-features/advanced-customization',
        'key-features/multi-protocol-flexibility',
        'key-features/permissionless-innovation',
        // Add more features
      ],
    },
     {
      type: 'category',
      label: 'Use Cases',
      items: [
        'use-cases/lenders',
        'use-cases/borrowers-strategic-lps',
        'use-cases/developers-flash-loans',
        'use-cases/vault-creators',
      ],
    },
    'technical-architecture', // Assuming a single file for now
    'governance',
    'security',
    'tokenomics', // Illustrative, from your whitepaper
    'roadmap',
    'community-engagement', // To house the "Engage with Yeap Finance" content
    // Add more top-level docs or categories here
  ],
};

export default sidebars;
