// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a custom sidebar to ensure the order and structure
  docsSidebar: [
    {
      type: 'category',
      label: 'Yeap Finance', // This category label itself won't be a direct link by default with this structure
      collapsible: true,     // Optional: allow collapsing
      collapsed: false,      // Optional: start uncollapsed (so it's open by default)
      items: [
        'overview',          // This refers to docs/overview.md (using its id or filename if id is not set)
        'introduction',      // Corresponds to docs/introduction.md
        'architecture',      // Corresponds to docs/architecture.md
      ],
    },
    {
      type: 'category',
      label: 'Core Components',
      collapsible: true,
      collapsed: true, // Start other categories collapsed if you prefer
      items: [
        'core-components/vaults',
        'core-components/borrow-protocols',
      ],
    },
    {
      type: 'category',
      label: 'Key Features',
      collapsible: true,
      collapsed: true,
      items: [
        'key-features/advanced-customization',
        'key-features/multi-protocol-flexibility',
        'key-features/permissionless-innovation',
      ],
    },
     {
      type: 'category',
      label: 'Use Cases',
      collapsible: true,
      collapsed: true,
      items: [
        'use-cases/lenders',
        'use-cases/borrowers-strategic-lps',
        'use-cases/developers-flash-loans',
        'use-cases/vault-creators',
      ],
    },
    'technical-architecture',
    'governance',
    'security',
    'tokenomics',
    'roadmap',
    'community-engagement',
  ],
};

export default sidebars;
